import {
  Building2,
  Users,
  Briefcase,
  LayoutDashboard,
  Calendar,
  Inbox,
  MessageSquare,
  Image as ImageIcon,
  Zap,
  FileText,
  BookOpen,
  ClipboardCheck,
  Ticket,
  BarChart2,
  ListTodo,
  Globe,
  Rocket,
  Code,
  Coffee,
  Heart,
  Star,
  Smile,
  Pencil,
  Search,
  Settings,
  Shield,
  Smartphone,
  Sun,
  Truck,
  Wifi,
  Target,
  Store,
  MapPin,
  Home,
  Package,
  Wrench,
  Camera,
  Music,
  Gamepad2,
  Palette,
} from "lucide-react"

import type { IconOption, ColorOption } from "./types.ts"

export const ICON_LIST: IconOption[] = [
  { name: "Building2", icon: Building2 },
  { name: "Briefcase", icon: Briefcase },
  { name: "Users", icon: Users },
  { name: "Globe", icon: Globe },
  { name: "Zap", icon: Zap },
  { name: "LayoutDashboard", icon: LayoutDashboard },
  { name: "Code", icon: Code },
  { name: "Coffee", icon: Coffee },
  { name: "Heart", icon: Heart },
  { name: "Star", icon: Star },
  { name: "Smile", icon: Smile },
  { name: "Rocket", icon: Rocket },
  { name: "Pencil", icon: Pencil },
  { name: "Search", icon: Search },
  { name: "Settings", icon: Settings },
  { name: "Shield", icon: Shield },
  { name: "Smartphone", icon: Smartphone },
  { name: "Sun", icon: Sun },
  { name: "Truck", icon: Truck },
  { name: "Wifi", icon: Wifi },
  { name: "Target", icon: Target },
  { name: "Store", icon: Store },
  { name: "MapPin", icon: MapPin },
  { name: "Home", icon: Home },
  { name: "Package", icon: Package },
  { name: "Wrench", icon: Wrench },
  { name: "Camera", icon: Camera },
  { name: "Music", icon: Music },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Palette", icon: Palette },
  { name: "Calendar", icon: Calendar },
  { name: "Inbox", icon: Inbox },
  { name: "MessageSquare", icon: MessageSquare },
  { name: "Image", icon: ImageIcon },
  { name: "FileText", icon: FileText },
  { name: "BookOpen", icon: BookOpen },
  { name: "ClipboardCheck", icon: ClipboardCheck },
  { name: "Ticket", icon: Ticket },
  { name: "BarChart2", icon: BarChart2 },
  { name: "ListTodo", icon: ListTodo },
]

export const COLORS: ColorOption[] = [
  { name: "Slate", value: "slate" },
  { name: "Red", value: "red" },
  { name: "Orange", value: "orange" },
  { name: "Amber", value: "amber" },
  { name: "Green", value: "green" },
  { name: "Teal", value: "teal" },
  { name: "Blue", value: "blue" },
  { name: "Indigo", value: "indigo" },
  { name: "Violet", value: "violet" },
  { name: "Pink", value: "pink" },
]
